### PR TITLE
chore: Fix lints

### LINKED ISSUE #90: Fix unreachable patterns

### PR DESCRIPTION
**Pull request by jayvdb**
Two lints silenced for https://github.com/smol-rs/async-lock/issues/90

Closes #90

### CODE REVIEW

File: src/once_cell.rs [hunk 1]
```diff
@@ -476,6 +476,7 @@ impl<T> OnceCell<T> {
     /// # });
     /// ```
     pub async fn get_or_init<Fut: Future<Output = T>>(&self, closure: impl FnOnce() -> Fut) -> &T {
+        #[allow(unreachable_patterns)]
```
Comment (taiki-e) [inline src/once_cell.rs:479]:
```suggestion
        #[allow(unreachable_patterns)] // false positive: https://github.com/rust-lang/rust/issues/129352
```
It would be nice to have a comment that shows why this is being ignored.

File: src/once_cell.rs [hunk 2]
```diff
@@ -517,6 +518,7 @@ impl<T> OnceCell<T> {
             let result: Result<T, Infallible> = Ok(closure());
             result
         });
+        #[allow(unreachable_patterns)]
```
Comment (taiki-e) [inline src/once_cell.rs:521]:
```suggestion
        #[allow(unreachable_patterns)] // false positive: https://github.com/rust-lang/rust/issues/129352
```

**Review by taiki-e — COMMENTED** [review]
Thanks!

File: src/once_cell.rs (hunk 1 above)
Comment (jayvdb) [reply src/once_cell.rs:480]: Added

**Review by taiki-e — APPROVED** [review]
